Fix predict_with_confidence return value unpacking in AdversarialTester
Bug: Line 964 tried to unpack dictionary as tuple:
  preds, _, _ = self.model.predict_with_confidence(...)

predict_with_confidence returns a dict, not a tuple. Unpacking a dict
gives you the keys (strings), not values. This caused:
  AttributeError: 'str' object has no attribute 'cpu'

Fix: Properly access the dictionary:
  result = self.model.predict_with_confidence(...)
  preds = result['predictions']